"""generate_paper_figures.py
=========================
Master script that regenerates every figure and CSV table used in Paper.tex.

Run from the project root:
    python generate_paper_figures.py \
        --experiments_root experiments \
        --results_dir results

Paper figure mapping
--------------------
Fig. 2  (fig:main_bars)              -> results/final_accuracy_bar.png
                                        results/macro_f1_bar.png
Fig. 3  (fig:val_acc_learning_curves)-> results/val_acc_learning_curves.png
Fig. 4  (fig:accuracy_over_time)     -> results/accuracy_over_time.png
Fig. 5  (fig:e4_epoch_trajectories)  -> results/checkpoint_sample_steps_<model>_seed_<s>_epoch_<N>.png
                                        (N = 20, 40, 80; model = dual_stream_stepwise_fusion)
Fig. 6  (fig:confusion)              -> results/cm_visual_only_epoch_20/40/80.png
                                        results/cm_stepwise_fusion_epoch_20/40/80.png

CSV tables used in paper
------------------------
Tab. 1  (tab:main)       -> results/main_table.csv      (pre-generated by evaluate.py)
Tab. 2  (epoch analysis) -> results/epoch_metrics_summary.csv
Tab. 3  (tab:complexity) -> results/main_table.csv  (param count column)
"""

import argparse
import json
import os
import sys

import torch


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _banner(msg: str) -> None:
    print(f"\n{'='*60}")
    print(f"  {msg}")
    print(f"{'='*60}")


# ---------------------------------------------------------------------------
# Import project modules (must run from project root or with PYTHONPATH set)
# ---------------------------------------------------------------------------

def _import_modules():
    """Import visualization helpers; fail early with a clear message."""
    try:
        import summarize_epoch_metrics as sem
        import visualize_results as vr
        import visualize_checkpoint_samples as vcs
        import evaluate as ev
        return sem, vr, vcs, ev
    except ImportError as exc:
        print(f"[ERROR] Could not import project modules: {exc}")
        print("  Make sure you run this script from the project root directory.")
        sys.exit(1)


# ---------------------------------------------------------------------------
# Step 0: Run evaluate.py to (re)generate main_table.csv  (Tab. 1 in paper)
# ---------------------------------------------------------------------------

def step_evaluate(ev, experiments_root: str, results_dir: str) -> None:
    _banner("Step 0 / 5 — evaluate.py → main_table.csv  (Tab. 1 in paper)")
    os.makedirs(results_dir, exist_ok=True)

    rows = ev._collect_run_summaries(experiments_root)
    if not rows:
        print("  [WARN] No run_summary.json files found. Skipping Tab. 1 / Fig. 2.")
        return

    ev._write_metrics_summary(results_dir, rows)
    main_table_csv = ev._write_main_table(results_dir, rows)
    ev._write_run_manifest(results_dir, rows)
    print(f"  Tab. 1 (tab:main) -> {main_table_csv}")
    print(f"  Found {len(rows)} seed runs across experiments.")


# ---------------------------------------------------------------------------
# Step 1: Epoch metrics CSV  (Tab. 2 in paper)
# ---------------------------------------------------------------------------

def step_epoch_metrics(sem, experiments_root: str, results_dir: str,
                       epochs: list) -> None:
    _banner("Step 1 / 6 — Epoch metrics CSV  (Tab. 2 in paper)")
    import types, sys as _sys
    # Build a mock args namespace and call sem.main directly via its logic
    from collections import namedtuple
    import csv
    from collections import defaultdict
    from statistics import mean

    histories = sem._collect_histories(experiments_root)
    if not histories:
        print("  [WARN] No history.json files found; skipping epoch metrics.")
        return

    raw_rows = []
    for exp_name, seed_name, history_path in histories:
        import json as _json
        with open(history_path, "r") as f:
            history = _json.load(f)
        for epoch_value in epochs:
            idx = epoch_value - 1  # 1-based
            if idx < 0 or idx >= len(history):
                raw_rows.append(dict(experiment_name=exp_name, seed=seed_name,
                                     epoch=epoch_value, available=0,
                                     val_loss="", val_final_accuracy="",
                                     val_macro_f1="", val_balanced_accuracy=""))
                continue
            row = history[idx]
            raw_rows.append(dict(experiment_name=exp_name, seed=seed_name,
                                  epoch=epoch_value, available=1,
                                  val_loss=row.get("val_loss", ""),
                                  val_final_accuracy=row.get("val_final_accuracy", ""),
                                  val_macro_f1=row.get("val_macro_f1", ""),
                                  val_balanced_accuracy=row.get("val_balanced_accuracy", "")))

    os.makedirs(results_dir, exist_ok=True)
    raw_csv = os.path.join(results_dir, "epoch_metrics_raw.csv")
    fields = ["experiment_name", "seed", "epoch", "available",
              "val_loss", "val_final_accuracy", "val_macro_f1", "val_balanced_accuracy"]
    with open(raw_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(raw_rows)
    print(f"  Wrote: {raw_csv}")

    grouped = defaultdict(list)
    for r in raw_rows:
        grouped[(r["experiment_name"], r["epoch"])].append(r)

    summary_rows = []
    for (exp_name, epoch_value), rows in sorted(grouped.items(), key=lambda x: (x[0][1], x[0][0])):
        valid = [r for r in rows if r["available"] == 1]
        if not valid:
            summary_rows.append(dict(experiment_name=exp_name, epoch=epoch_value,
                                     n_available_seeds=0, val_loss_mean="", val_loss_std="",
                                     val_final_accuracy_mean="", val_final_accuracy_std="",
                                     val_macro_f1_mean="", val_macro_f1_std="",
                                     val_balanced_accuracy_mean="", val_balanced_accuracy_std=""))
            continue
        from statistics import pstdev
        def _std(v): return 0.0 if len(v) <= 1 else pstdev(v)
        val_loss = [float(r["val_loss"]) for r in valid]
        val_acc  = [float(r["val_final_accuracy"]) for r in valid]
        val_f1   = [float(r["val_macro_f1"]) for r in valid]
        val_bal  = [float(r["val_balanced_accuracy"]) for r in valid]
        summary_rows.append(dict(experiment_name=exp_name, epoch=epoch_value,
                                  n_available_seeds=len(valid),
                                  val_loss_mean=mean(val_loss), val_loss_std=_std(val_loss),
                                  val_final_accuracy_mean=mean(val_acc), val_final_accuracy_std=_std(val_acc),
                                  val_macro_f1_mean=mean(val_f1), val_macro_f1_std=_std(val_f1),
                                  val_balanced_accuracy_mean=mean(val_bal), val_balanced_accuracy_std=_std(val_bal)))

    summary_csv = os.path.join(results_dir, "epoch_metrics_summary.csv")
    sfields = ["experiment_name", "epoch", "n_available_seeds",
               "val_loss_mean", "val_loss_std",
               "val_final_accuracy_mean", "val_final_accuracy_std",
               "val_macro_f1_mean", "val_macro_f1_std",
               "val_balanced_accuracy_mean", "val_balanced_accuracy_std"]
    with open(summary_csv, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=sfields)
        w.writeheader()
        w.writerows(summary_rows)
    print(f"  Wrote: {summary_csv}")


# ---------------------------------------------------------------------------
# Step 2: Main bar charts + learning curves + accuracy-over-time  (Fig 2,3,4)
# ---------------------------------------------------------------------------

def step_static_figures(vr, experiments_root: str, results_dir: str) -> None:
    _banner("Step 2 / 6 — Static figures  (Fig. 2, 3, 4 in paper)")
    os.makedirs(results_dir, exist_ok=True)

    main_table_csv = os.path.join(results_dir, "main_table.csv")
    if not os.path.exists(main_table_csv):
        print(f"  [WARN] main_table.csv not found at {main_table_csv}")
        print("  Skipping Fig. 2 (main bar charts). Run evaluate.py first.")
    else:
        # Fig. 2 — Main comparison bar charts
        out1, out2 = vr.plot_main_bars(main_table_csv, results_dir)
        print(f"  Fig. 2 (fig:main_bars) -> {out1}")
        print(f"  Fig. 2 (fig:main_bars) -> {out2}")

    # Fig. 3 — Validation accuracy learning curves
    lc = vr.plot_val_accuracy_learning_curves(experiments_root, results_dir)
    if lc:
        print(f"  Fig. 3 (fig:val_acc_learning_curves) -> {lc}")
    else:
        print("  [WARN] Fig. 3: no learning curve data found.")

    # Fig. 4 — Accuracy over time steps
    ot = vr.plot_accuracy_over_time(experiments_root, results_dir)
    if ot:
        print(f"  Fig. 4 (fig:accuracy_over_time) -> {ot}")
    else:
        print("  [WARN] Fig. 4: no accuracy-over-time data found.")


# ---------------------------------------------------------------------------
# Step 3: Epoch trajectory plots for E4 stepwise fusion  (Fig. 5)
# ---------------------------------------------------------------------------

def step_epoch_trajectories(vcs, experiments_root: str, results_dir: str,
                             seed: int, epochs: list, device: torch.device,
                             eval_batch_size: int) -> None:
    _banner("Step 3 / 6 — Epoch trajectory plots E4  (Fig. 5 in paper)")
    os.makedirs(results_dir, exist_ok=True)
    exp_name = "dual_stream_stepwise_fusion"

    try:
        run_dir = vcs.resolve_run_dir(experiments_root, exp_name, seed)
        cfg = vcs.load_run_config(run_dir)
        checkpoints = vcs.build_checkpoint_list("best.pt", epochs)

        for ckpt_name in checkpoints:
            model = vcs.build_model(cfg, device)
            ckpt_path = vcs.resolve_checkpoint_path(run_dir, ckpt_name)
            ckpt = torch.load(ckpt_path, map_location=device)
            model.load_state_dict(ckpt["model_state"])

            val_loader = vcs.build_val_loader_from_config(cfg, eval_batch_size=eval_batch_size)
            records = vcs.collect_sample_trajectories(model, val_loader, device)

            del model
            if torch.cuda.is_available():
                torch.cuda.empty_cache()

            tag = vcs.checkpoint_tag(ckpt_name)
            out_csv = os.path.join(results_dir, f"checkpoint_sample_steps_{exp_name}_seed_{seed}_{tag}.csv")
            import pandas as pd
            pd.DataFrame(records).to_csv(out_csv, index=False)

            out_png = os.path.join(results_dir, f"checkpoint_sample_steps_{exp_name}_seed_{seed}_{tag}.png")
            plot_records = vcs.select_records_for_plot(records, max_samples=10)
            vcs.render_sample_plot(plot_records, out_png)

            print(f"  Fig. 5 (fig:e4_epoch_trajectories) -> {out_png}")
            print(f"  CSV data -> {out_csv}")
    except Exception as e:
        print(f"  [WARN] Fig. 5 FAILED: {e}")


# ---------------------------------------------------------------------------
# Step 4: Epoch-based confusion matrices  (Fig. 6)
# ---------------------------------------------------------------------------

def step_epoch_confusion_matrices(vcs, experiments_root: str, results_dir: str,
                                   seed: int, epochs: list, device: torch.device,
                                   eval_batch_size: int) -> None:
    _banner("Step 4 / 6 — Epoch confusion matrices  (Fig. 6 in paper)")
    os.makedirs(results_dir, exist_ok=True)

    # E1 and E4: the two models shown in Fig. 6
    exp_names = ["visual_only", "dual_stream_stepwise_fusion"]
    out_paths = vcs.plot_epoch_confusion_matrices(
        experiments_root=experiments_root,
        results_dir=results_dir,
        exp_names=exp_names,
        seed=seed,
        epochs=epochs,
        device=device,
        eval_batch_size=eval_batch_size,
    )
    for p in out_paths:
        print(f"  Fig. 6 (fig:confusion) -> {p}")


# ---------------------------------------------------------------------------
# Step 5: Write figure manifest
# ---------------------------------------------------------------------------

def step_manifest(results_dir: str) -> None:
    _banner("Step 5 / 6 — Writing figure manifest")
    import glob
    pngs = sorted(glob.glob(os.path.join(results_dir, "*.png")))
    csvs = sorted(glob.glob(os.path.join(results_dir, "*.csv")))
    manifest = {"figures": pngs, "tables": csvs}
    manifest_path = os.path.join(results_dir, "figures_manifest.json")
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    print(f"  Manifest written: {manifest_path}")
    print(f"  Total PNGs: {len(pngs)}, Total CSVs: {len(csvs)}")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Regenerate all paper figures and CSV tables for Paper.tex"
    )
    parser.add_argument("--experiments_root", type=str, required=True,
                        help="Root directory containing per-model experiment subdirectories")
    parser.add_argument("--results_dir", type=str, required=True,
                        help="Output directory for figures and CSVs (matches Paper.tex paths)")
    parser.add_argument("--epochs", type=int, nargs="+", default=[20, 40, 80],
                        help="Epoch checkpoints used for trajectory and CM figures")
    parser.add_argument("--seed", type=int, default=42,
                        help="Seed used for checkpoint-based plots (trajectory + CM)")
    parser.add_argument("--eval_batch_size", type=int, default=16)
    parser.add_argument("--skip_checkpoint_steps", action="store_true",
                        help="Skip steps 3+4 (require GPU/model checkpoints)")
    args = parser.parse_args()

    sem, vr, vcs, ev = _import_modules()

    # Add trainer.build_model to vcs namespace so step functions can call it
    try:
        from trainer import build_model  # type: ignore
        vcs.build_model = build_model
    except ImportError:
        if not args.skip_checkpoint_steps:
            print("[ERROR] Could not import trainer.build_model. "
                  "Use --skip_checkpoint_steps to skip GPU steps.")
            sys.exit(1)

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    print(f"\nDevice: {device}")
    print(f"Experiments root: {args.experiments_root}")
    print(f"Results dir:      {args.results_dir}")
    print(f"Epochs:           {args.epochs}")
    print(f"Seed:             {args.seed}")

    step_evaluate(ev, args.experiments_root, args.results_dir)
    step_epoch_metrics(sem, args.experiments_root, args.results_dir, args.epochs)
    step_static_figures(vr, args.experiments_root, args.results_dir)

    if not args.skip_checkpoint_steps:
        step_epoch_trajectories(vcs, args.experiments_root, args.results_dir,
                                args.seed, args.epochs, device, args.eval_batch_size)
        step_epoch_confusion_matrices(vcs, args.experiments_root, args.results_dir,
                                      args.seed, args.epochs, device, args.eval_batch_size)
    else:
        print("\n[INFO] Skipped checkpoint-based steps (--skip_checkpoint_steps).")

    step_manifest(args.results_dir)

    print("\nAll done. Figures are in:", args.results_dir)
    print("\nPaper figure mapping summary:")
    print("  Fig. 2  (fig:main_bars)               <- final_accuracy_bar.png, macro_f1_bar.png")
    print("  Fig. 3  (fig:val_acc_learning_curves) <- val_acc_learning_curves.png")
    print("  Fig. 4  (fig:accuracy_over_time)      <- accuracy_over_time.png")
    print("  Fig. 5  (fig:e4_epoch_trajectories)   <- checkpoint_sample_steps_*_epoch_{20,40,80}.png")
    print("  Fig. 6  (fig:confusion)               <- cm_{visual_only,stepwise_fusion}_epoch_{20,40,80}.png")
    print("  Tab. 1  (tab:main)                    <- main_table.csv")
    print("  Tab. 2  (epoch analysis)              <- epoch_metrics_summary.csv")


if __name__ == "__main__":
    main()
